server:
  port: 8080

spring:
  application:
    name: ordered-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: http://localhost:9091
              predicates:
                - Path=/api/v1/orders/**,/api/v1/payments/**
            - id: product-service-route
              uri: http://localhost:9092
              predicates:
                - Path=/api/v1/products/**,/api/v1/cart/**
            - id: engagement-service-route
              uri: http://localhost:9094
              predicates:
                - Path=/api/v1/reviews/**,/api/v1/browsing-history/**
            - id: user-service-route
              uri: http://localhost:9093
              predicates:
                - Path=/api/v1/users/**,/api/v1/auth/**,/api/v1/addresses/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

ordered:
  gateway:
    security:
      jwt-secret: ${JWT_SECRET:change-me-in-prod-min-256-bits-long-please-replace}
      public-paths:
        - /api/v1/auth/**
        - /actuator/**
        - /api/v1/products/**
        - /api/v1/products
        - /api/v1/reviews/product/**
        - /swagger-ui/**
        - /v3/api-docs/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO